baseurl: "/" 
url: "https://smartcontractecosystem.com/" 

heading: Smart Contract Ecosystem
copyright:  
  year: 2021
  msg: Chainlink Labs

preferences:
  search:
    enabled: true
    shortcut_hint: 
        enabled: true
  wiki_style_link:
    enabled: true
  sidenotes: 
    enabled: true
  transclusion:
    enabled: true
  image:
    enabled: true
  pagepreview:
    enabled: true
  highlighting:
    enabled: true
    color: DAEDFF 
  backlinks:
    enabled: true
  related:
    enabled: false
  wrapping:
    enabled: true
  contextmenu:
    enabled: false
    copylink: 
      enabled: false
    newtab: 
      enabled: false
    backlinks: 
      enabled: false
    related: 
      enabled: false
  flashcards:
    enabled: false
  homepage: 
    enabled: true

encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap 
  - jekyll-tidy

## Enable _notes Collection 
collections:
    notes:
      output: false
      permalink: /notes/:title      
# Disqus Comments
disqus:
    shortname: 

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: katex
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge
  
sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: Post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: Post
      content-type: notes


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
